# Generated by Django 4.2.4 on 2023-08-29 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductTracking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "courierName",
                    models.CharField(
                        blank=True, default="n/a", max_length=50, null=True
                    ),
                ),
                (
                    "trackingID",
                    models.CharField(
                        blank=True, default="n/a", max_length=50, null=True
                    ),
                ),
                (
                    "orderSent",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="store.customer",
                    ),
                ),
                (
                    "orderItem",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="store.orderitem",
                    ),
                ),
            ],
        ),
    ]
