# Generated by Django 4.2.2 on 2023-07-13 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_remove_product_customers"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.IntegerField(
                choices=[(1, "Phones"), (2, "Laptops"), (3, "Tablets")], null=True
            ),
        ),
    ]
