# Generated by Django 4.2.2 on 2023-07-13 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_product_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.IntegerField(
                choices=[(1, "Phones"), (2, "Laptops"), (3, "Tablets"), (4, "Digital")],
                null=True,
            ),
        ),
    ]
