# Generated by Django 4.2.2 on 2023-07-05 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_alter_product_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="seller",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
